-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO AS I
JOIN FISH_NAME_INFO AS N ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.LENGTH = (SELECT MAX(LENGTH)
                  FROM FISH_INFO
                  WHERE FISH_TYPE = I.FISH_TYPE)
ORDER BY I.ID;